import { Inter } from "next/font/google";
import Sidebar from "./_comps/sidebar"
const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({ children }) {
  return (
   
      <div className={inter.className} style={{ fontFamily: "myfont2" }}>
        <div className="flex"> <Sidebar className="w-[200px]"/>  {children}</div>
      
       
      </div>
  );
}
