import { Inter } from "next/font/google";
import "./globals.css";
import Hero from "./_components/Hero";
import Footer from "./_components/Footer";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
//imports
import Header from "./_components/Header";
//import Hero from "./_components/Hero";
const inter = Inter({ subsets: ["latin"] });

//export const metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className} style={{ fontFamily: "myfont2" }}>
          <Header />
          <Hero />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
